### ISSUE TITLE
Wish: Compile dt 4.0 on ubuntu 20

### ISSUE THREAD

**Issue by springm** [per2jensen/dt-on-ubuntu#2]
Per,
thanks for the good work! I was happily compiling dt 3.9xx under Ubuntu 20, to which I am tied for work related reasons for some more months.
Any chance you could update the scripts to allow compiling 4.0 under Ubuntu 20?

Best regards - Markus

**Comment by per2jensen** [comment]
Hi Markus,
 
I have build DT4 on Ubuntu 20.04 - there are for sure some issues. Please see the READM.md

result from the compile in a vm:

======================================

this is darktable 4.0.0
copyright (c) 2009-2022 johannes hanika
darktable-dev@lists.darktable.org

compile options:
  bit depth is 64 bit
  normal build
  SSE2 optimized codepath enabled
  OpenMP support enabled
  OpenCL support enabled
  Lua support disabled
  Colord support enabled
  gPhoto2 support enabled
  GraphicsMagick support enabled
  ImageMagick support disabled
  OpenEXR support enabled


Hope this can help you, I am curious if the DT4 is of any use to you.
